apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - ../base

namePrefix: openclaw-

commonLabels:
  app: openclaw
  managed-by: kustomize

commonAnnotations:
  deployment-tool: kustomize
